version: '3.8'

services:
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db.sql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'api'
      MYSQL_ROOT_PASSWORD: 'api'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
volumes:
  db: