fifty_level_scenario = [
    {
        "id": 5,
        "name": "nest_five_1",
        "children": [
            {
                "id": 6,
                "name": "nest_child_five_2",
                "children": [
                    {
                        "id": 7,
                        "name": "nest_child_five_3",
                        "children": [
                            {
                                "id": 8,
                                "name": "nest_child_five_4",
                                "children": [
                                    {
                                        "id": 9,
                                        "name": "nest_child_five_5",
                                        "children": [
                                            {
                                                "id": 10,
                                                "name": "nest_child_five_6",
                                                "children": [
                                                    {
                                                        "id": 11,
                                                        "name": "nest_child_five_7",
                                                        "children": [
                                                            {
                                                                "id": 12,
                                                                "name": "nest_child_five_8",
                                                                "children": [
                                                                    {
                                                                        "id": 13,
                                                                        "name": "nest_child_five_9",
                                                                        "children": [
                                                                            {
                                                                                "id": 14,
                                                                                "name": "nest_child_five_10",
                                                                                "children": [
                                                                                    {
                                                                                        "id": 15,
                                                                                        "name": "nest_child_five_11",
                                                                                        "children": [
                                                                                            {
                                                                                                "id": 16,
                                                                                                "name": "nest_child_five_12",
                                                                                                "children": [
                                                                                                    {
                                                                                                        "id": 17,
                                                                                                        "name": "nest_child_five_13",
                                                                                                        "children": [
                                                                                                            {
                                                                                                                "id": 18,
                                                                                                                "name": "nest_child_five_14",
                                                                                                                "children": [
                                                                                                                    {
                                                                                                                        "id": 19,
                                                                                                                        "name": "nest_child_five_15",
                                                                                                                        "children": [
                                                                                                                            {
                                                                                                                                "id": 20,
                                                                                                                                "name": "nest_child_five_16",
                                                                                                                                "children": [
                                                                                                                                    {
                                                                                                                                        "id": 21,
                                                                                                                                        "name": "nest_child_five_17",
                                                                                                                                        "children": [
                                                                                                                                            {
                                                                                                                                                "id": 22,
                                                                                                                                                "name": "nest_child_five_18",
                                                                                                                                                "children": [
                                                                                                                                                    {
                                                                                                                                                        "id": 23,
                                                                                                                                                        "name": "nest_child_five_19",
                                                                                                                                                        "children": [
                                                                                                                                                            {
                                                                                                                                                                "id": 24,
                                                                                                                                                                "name": "nest_child_five_20",
                                                                                                                                                                "children": [
                                                                                                                                                                    {
                                                                                                                                                                        "id": 25,
                                                                                                                                                                        "name": "nest_child_five_21",
                                                                                                                                                                        "children": [
                                                                                                                                                                            {
                                                                                                                                                                                "id": 26,
                                                                                                                                                                                "name": "nest_child_five_22",
                                                                                                                                                                                "children": [
                                                                                                                                                                                    {
                                                                                                                                                                                        "id": 27,
                                                                                                                                                                                        "name": "nest_child_five_23",
                                                                                                                                                                                        "children": [
                                                                                                                                                                                            {
                                                                                                                                                                                                "id": 28,
                                                                                                                                                                                                "name": "nest_child_five_24",
                                                                                                                                                                                                "children": [
                                                                                                                                                                                                    {
                                                                                                                                                                                                        "id": 29,
                                                                                                                                                                                                        "name": "nest_child_five_25",
                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                            {
                                                                                                                                                                                                                "id": 30,
                                                                                                                                                                                                                "name": "nest_child_five_26",
                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                    {
                                                                                                                                                                                                                        "id": 31,
                                                                                                                                                                                                                        "name": "nest_child_five_27",
                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                "id": 32,
                                                                                                                                                                                                                                "name": "nest_child_five_28",
                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                        "id": 33,
                                                                                                                                                                                                                                        "name": "nest_child_five_29",
                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                "id": 34,
                                                                                                                                                                                                                                                "name": "nest_child_five_30",
                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                        "id": 35,
                                                                                                                                                                                                                                                        "name": "nest_child_five_31",
                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                "id": 36,
                                                                                                                                                                                                                                                                "name": "nest_child_five_32",
                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                        "id": 37,
                                                                                                                                                                                                                                                                        "name": "nest_child_five_33",
                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                "id": 38,
                                                                                                                                                                                                                                                                                "name": "nest_child_five_34",
                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                        "id": 39,
                                                                                                                                                                                                                                                                                        "name": "nest_child_five_35",
                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                "id": 40,
                                                                                                                                                                                                                                                                                                "name": "nest_child_five_36",
                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                        "id": 41,
                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_37",
                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                "id": 42,
                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_38",
                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                        "id": 43,
                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_39",
                                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                "id": 44,
                                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_40",
                                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                        "id": 45,
                                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_41",
                                                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                "id": 46,
                                                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_42",
                                                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                        "id": 47,
                                                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_43",
                                                                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                "id": 48,
                                                                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_44",
                                                                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                        "id": 49,
                                                                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_45",
                                                                                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                "id": 50,
                                                                                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_46",
                                                                                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                        "id": 51,
                                                                                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_47",
                                                                                                                                                                                                                                                                                                                                                                                        "children": [
                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                "id": 52,
                                                                                                                                                                                                                                                                                                                                                                                                "name": "nest_child_five_48",
                                                                                                                                                                                                                                                                                                                                                                                                "children": [
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                        "id": 53,
                                                                                                                                                                                                                                                                                                                                                                                                        "name": "nest_child_five_49",
                                                                                                                                                                                                                                                                                                                                                                                                        "children": []
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                ]
                                                                                                                                                                                                            }
                                                                                                                                                                                                        ]
                                                                                                                                                                                                    }
                                                                                                                                                                                                ]
                                                                                                                                                                                            }
                                                                                                                                                                                        ]
                                                                                                                                                                                    }
                                                                                                                                                                                ]
                                                                                                                                                                            }
                                                                                                                                                                        ]
                                                                                                                                                                    }
                                                                                                                                                                ]
                                                                                                                                                            }
                                                                                                                                                        ]
                                                                                                                                                    }
                                                                                                                                                ]
                                                                                                                                            }
                                                                                                                                        ]
                                                                                                                                    }
                                                                                                                                ]
                                                                                                                            }
                                                                                                                        ]
                                                                                                                    }
                                                                                                                ]
                                                                                                            }
                                                                                                        ]
                                                                                                    }
                                                                                                ]
                                                                                            }
                                                                                        ]
                                                                                    }
                                                                                ]
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
]